/* Automatically generated by './build/bin/build-entry.js' */

import SelectDatePicker from '../packages/select-date-picker/index.js';
import TablePagination from '../packages/table-pagination/index.js';
import SelectPicker from '../packages/select-picker/index.js';

const components = [
  SelectDatePicker,
  TablePagination,
  SelectPicker
];

const install = function(Vue, opts = {}) {
  components.map(component => {
    Vue.component(component.name, component);
  });

  const ELEMENT = {};
  ELEMENT.size = opts.size || '';

  Vue.prototype.$ELEMENT = ELEMENT;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
};

module.exports = {
  version: '2.0.0',
  install,
  SelectDatePicker,
  TablePagination,
  SelectPicker
};

module.exports.default = module.exports;
